paths:  # paths in which to search (recursively) for recordings
  - "./InterviewRecordings"

transcription:
  silence_dropoff_threshold: 32  # how far below peak volume counts as a break between words
  chunk_length: 7  # min size of chunks transcribed
  chunk_skip: 4  # min skip between chunks

embedding:
  processing_batch_size: 100  # batch size for sending text to huggingface for embedding
  front_to_whole_weighting: 0.4  # how much to weight the first few words (0) vs the whole text chunk (1)
  num_words_to_front_weight: 7  # how many words is the "first few words"
